// Seed Data for Sakanak
// بيانات واقعية للسكنات في مختلف الجامعات المصرية

import type { Property, Review, Booking, OwnerStats } from '@/types';

export const seedProperties: Partial<Property>[] = [
  // القاهرة - جامعة القاهرة
  {
    id: 'prop-001',
    title: 'سرير في غرفة مفروشة مشتركة',
    description: 'سرير مريح في غرفة مشتركة مفروشة بالكامل. الغرفة تتسع لـ3 طلاب، فيها تكييف وإنترنت عالي السرعة. المبنى قريب من بوابة جامعة القاهرة الرئيسية.',
    price: 800,
    priceType: 'per_bed',
    location: 'الجيزة، شارع النصر، عمارة 15',
    city: 'القاهرة',
    coordinates: { lat: 30.0237, lng: 31.2086 },
    nearTo: ['جامعة القاهرة', 'كلية الطب القصر العيني'],
    distanceTo: { university: 'جامعة القاهرة', distance: 2.0 },
    type: 'shared_bed',
    rooms: 1,
    beds: 3,
    bathrooms: 1,
    amenities: ['wifi', 'ac', 'kitchen', 'laundry', 'security'],
    images: [
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800',
      'https://images.unsplash.com/photo-1522771753035-a0a1f66cd459?w=800',
    ],
    verified: true,
    featured: true,
    available: true,
    ownerId: 'owner-001',
  },
  {
    id: 'prop-002',
    title: 'غرفة خاصة في شقة مشتركة',
    description: 'غرفة خاصة واسعة في شقة مشتركة مع طلاب هادئين. الشقة مفروشة بالكامل، فيها مطبخ مجهز وحمام مشترك. قريبة من مترو جامعة القاهرة.',
    price: 1500,
    priceType: 'per_room',
    location: 'الدقي، شارع محمود عزمي، عمارة 7',
    city: 'القاهرة',
    coordinates: { lat: 30.0385, lng: 31.2135 },
    nearTo: ['جامعة القاهرة', 'عين شمس'],
    distanceTo: { university: 'جامعة القاهرة', distance: 3.0 },
    type: 'private_room',
    rooms: 3,
    beds: 4,
    bathrooms: 2,
    amenities: ['wifi', 'ac', 'kitchen', 'laundry', 'security', 'elevator'],
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    verified: true,
    featured: false,
    available: true,
    ownerId: 'owner-002',
  },
  {
    id: 'prop-003',
    title: 'سرير في سكن طلابي حديث',
    description: 'سرير في سكن طلابي حديث بمدينة نصر. المكان آمن ومنظم، فيه إنترنت فايبر وغسالات مشتركة. مناسب لطلاب AUC.',
    price: 600,
    priceType: 'per_bed',
    location: 'مدينة نصر، شارع عباس العقاد، عمارة 45',
    city: 'القاهرة',
    coordinates: { lat: 30.0566, lng: 31.3304 },
    nearTo: ['AUC', 'جامعة عين شمس'],
    distanceTo: { university: 'AUC', distance: 4.0 },
    type: 'shared_bed',
    rooms: 2,
    beds: 4,
    bathrooms: 1,
    amenities: ['wifi', 'ac', 'kitchen', 'laundry', 'security'],
    images: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
      'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800',
    ],
    verified: true,
    featured: false,
    available: true,
    ownerId: 'owner-003',
  },
  {
    id: 'prop-004',
    title: 'شقة صغيرة مفروشة للإيجار',
    description: 'شقة استوديو صغيرة مفروشة بالكامل في الدقي. مناسبة لطالب يحب الخصوصية. قريبة من الجامعة الأمريكية والنيل.',
    price: 2500,
    priceType: 'per_apartment',
    location: 'الدقي، شارع مراد، عمارة 12',
    city: 'القاهرة',
    coordinates: { lat: 30.0419, lng: 31.2105 },
    nearTo: ['AUC', 'جامعة القاهرة'],
    distanceTo: { university: 'AUC', distance: 1.5 },
    type: 'full_apartment',
    rooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ['wifi', 'ac', 'kitchen', 'security', 'elevator'],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    verified: true,
    featured: true,
    available: true,
    ownerId: 'owner-004',
  },
  {
    id: 'prop-005',
    title: 'غرفة خاصة مع حمام داخلي',
    description: 'غرفة فاخرة مع حمام داخلي في شقة حديثة بالتجمع الخامس. قريبة من الجامعات الأجنبية والمستشفيات.',
    price: 3000,
    priceType: 'per_room',
    location: 'التجمع الخامس، شارع التسعين، كمبوند صن سيتي',
    city: 'القاهرة',
    coordinates: { lat: 30.0169, lng: 31.4116 },
    nearTo: ['AUC', 'الجامعة الألمانية'],
    distanceTo: { university: 'AUC', distance: 3.5 },
    type: 'private_room',
    rooms: 3,
    beds: 3,
    bathrooms: 3,
    amenities: ['wifi', 'ac', 'kitchen', 'laundry', 'security', 'gym', 'parking'],
    images: [
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800',
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800',
    ],
    verified: true,
    featured: true,
    available: true,
    ownerId: 'owner-005',
  },

  // الإسكندرية
  {
    id: 'prop-006',
    title: 'سرير بجانب البحر مباشرة',
    description: 'سرير في غرفة مشتركة بإطلالة بحر رائعة! المكان هادئ وآمن، قريب من جامعة الإسكندرية. فيه إنترنت وتكييف.',
    price: 700,
    priceType: 'per_bed',
    location: 'الإسكندرية، محطة الرمل، شارع صلاح سالم، عمارة 8',
    city: 'الإسكندرية',
    coordinates: { lat: 31.2001, lng: 29.9187 },
    nearTo: ['جامعة الإسكندرية', 'الجامعة الفرنسية'],
    distanceTo: { university: 'جامعة الإسكندرية', distance: 1.5 },
    type: 'shared_bed',
    rooms: 2,
    beds: 4,
    bathrooms: 1,
    amenities: ['wifi', 'ac', 'kitchen', 'laundry', 'security'],
    images: [
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    ],
    verified: true,
    featured: true,
    available: true,
    ownerId: 'owner-006',
  },
  {
    id: 'prop-007',
    title: 'غرفة في سكن مشترك بسموحة',
    description: 'غرفة واسعة في سكن مشترك بمنطقة سموحة الراقية. قريبة من الجامعة الفرنسية والمحلات التجارية.',
    price: 1200,
    priceType: 'per_room',
    location: 'الإسكندرية، سموحة، شارع فيكتور عمانويل، عمارة 22',
    city: 'الإسكندرية',
    coordinates: { lat: 31.2156, lng: 29.9553 },
    nearTo: ['الجامعة الفرنسية', 'جامعة الإسكندرية'],
    distanceTo: { university: 'الجامعة الفرنسية', distance: 0.8 },
    type: 'private_room',
    rooms: 4,
    beds: 5,
    bathrooms: 2,
    amenities: ['wifi', 'ac', 'kitchen', 'laundry', 'security', 'elevator'],
    images: [
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    verified: true,
    featured: false,
    available: true,
    ownerId: 'owner-007',
  },
  {
    id: 'prop-008',
    title: 'شقة كاملة قرب الكورنيش',
    description: 'شقة مفروشة بالكامل قرب كورنيش الإسكندرية. غرفتين وصالة، مناسبة لمجموعة طلاب.',
    price: 2800,
    priceType: 'per_apartment',
    location: 'الإسكندرية، العصافرة، شارع 45، عمارة 10',
    city: 'الإسكندرية',
    coordinates: { lat: 31.2707, lng: 30.0055 },
    nearTo: ['جامعة الإسكندرية'],
    distanceTo: { university: 'جامعة الإسكندرية', distance: 4.0 },
    type: 'full_apartment',
    rooms: 2,
    beds: 3,
    bathrooms: 1,
    amenities: ['wifi', 'ac', 'kitchen', 'laundry', 'security'],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800',
    ],
    verified: true,
    featured: false,
    available: true,
    ownerId: 'owner-008',
  },

  // المنصورة
  {
    id: 'prop-009',
    title: 'سرير في غرفة مزدوجة قرب الجامعة',
    description: 'سرير في غرفة مزدوجة على بعد 500 متر من جامعة المنصورة. المكان هادئ ومناسب للمذاكرة.',
    price: 550,
    priceType: 'per_bed',
    location: 'المنصورة، شارع الجامعة، عمارة 3',
    city: 'المنصورة',
    coordinates: { lat: 31.0364, lng: 31.3807 },
    nearTo: ['جامعة المنصورة'],
    distanceTo: { university: 'جامعة المنصورة', distance: 0.5 },
    type: 'shared_bed',
    rooms: 1,
    beds: 2,
    bathrooms: 1,
    amenities: ['wifi', 'ac', 'kitchen', 'laundry'],
    images: [
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800',
      'https://images.unsplash.com/photo-1522771753035-a0a1f66cd459?w=800',
    ],
    verified: true,
    featured: false,
    available: true,
    ownerId: 'owner-009',
  },
  {
    id: 'prop-010',
    title: 'غرفة خاصة بالمنصورة الجديدة',
    description: 'غرفة خاصة واسعة في المنصورة الجديدة. المبنى حديث وآمن، قريب من الجامعة.',
    price: 1000,
    priceType: 'per_room',
    location: 'المنصورة الجديدة، الحي الثاني، عمارة 15',
    city: 'المنصورة',
    coordinates: { lat: 31.0286, lng: 31.4074 },
    nearTo: ['جامعة المنصورة'],
    distanceTo: { university: 'جامعة المنصورة', distance: 2.0 },
    type: 'private_room',
    rooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ['wifi', 'ac', 'kitchen', 'security', 'elevator'],
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    verified: true,
    featured: false,
    available: true,
    ownerId: 'owner-010',
  },

  // طنطا
  {
    id: 'prop-011',
    title: 'سرير في سكن طلابي منظم',
    description: 'سرير في سكن طلابي منظم قرب جامعة طنطا. المكان آمن ونظيف، فيه إنترنت وتكييف.',
    price: 500,
    priceType: 'per_bed',
    location: 'طنطا، شارع الجيش، عمارة 20',
    city: 'طنطا',
    coordinates: { lat: 30.7865, lng: 31.0004 },
    nearTo: ['جامعة طنطا'],
    distanceTo: { university: 'جامعة طنطا', distance: 1.0 },
    type: 'shared_bed',
    rooms: 3,
    beds: 6,
    bathrooms: 2,
    amenities: ['wifi', 'ac', 'kitchen', 'laundry', 'security'],
    images: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
      'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800',
    ],
    verified: true,
    featured: false,
    available: true,
    ownerId: 'owner-011',
  },
  {
    id: 'prop-012',
    title: 'غرفة خاصة بوسط المدينة',
    description: 'غرفة خاصة في وسط طنطا، قريبة من الجامعة والأسواق.',
    price: 900,
    priceType: 'per_room',
    location: 'طنطا، شارع النحاس، عمارة 5',
    city: 'طنطا',
    coordinates: { lat: 30.7915, lng: 30.9954 },
    nearTo: ['جامعة طنطا'],
    distanceTo: { university: 'جامعة طنطا', distance: 1.5 },
    type: 'private_room',
    rooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ['wifi', 'ac', 'kitchen', 'security'],
    images: [
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800',
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800',
    ],
    verified: true,
    featured: false,
    available: true,
    ownerId: 'owner-012',
  },

  // أسيوط
  {
    id: 'prop-013',
    title: 'سرير في سكن اقتصادي',
    description: 'سرير في سكن اقتصادي قرب جامعة أسيوط. مناسب للطلاب المقيدين مادياً.',
    price: 450,
    priceType: 'per_bed',
    location: 'أسيوط، شارع الجامعة، عمارة 8',
    city: 'أسيوط',
    coordinates: { lat: 27.1783, lng: 31.1859 },
    nearTo: ['جامعة أسيوط'],
    distanceTo: { university: 'جامعة أسيوط', distance: 1.2 },
    type: 'shared_bed',
    rooms: 2,
    beds: 4,
    bathrooms: 1,
    amenities: ['wifi', 'kitchen', 'laundry'],
    images: [
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800',
      'https://images.unsplash.com/photo-1522771753035-a0a1f66cd459?w=800',
    ],
    verified: true,
    featured: false,
    available: true,
    ownerId: 'owner-013',
  },
  {
    id: 'prop-014',
    title: 'غرفة خاصة مكيفة',
    description: 'غرفة خاصة مكيفة في منطقة هادئة قرب الجامعة.',
    price: 800,
    priceType: 'per_room',
    location: 'أسيوط، الحي الثامن، عمارة 12',
    city: 'أسيوط',
    coordinates: { lat: 27.1833, lng: 31.1909 },
    nearTo: ['جامعة أسيوط'],
    distanceTo: { university: 'جامعة أسيوط', distance: 2.0 },
    type: 'private_room',
    rooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ['wifi', 'ac', 'kitchen', 'security'],
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    verified: true,
    featured: false,
    available: true,
    ownerId: 'owner-014',
  },

  // قنا
  {
    id: 'prop-015',
    title: 'سرير في سكن طلابي بسيط',
    description: 'سرير في سكن طلابي بسيط ونظيف قرب جامعة قنا.',
    price: 400,
    priceType: 'per_bed',
    location: 'قنا، شارع الجامعة، عمارة 3',
    city: 'قنا',
    coordinates: { lat: 26.1551, lng: 32.716 },
    nearTo: ['جامعة قنا'],
    distanceTo: { university: 'جامعة قنا', distance: 0.8 },
    type: 'shared_bed',
    rooms: 2,
    beds: 4,
    bathrooms: 1,
    amenities: ['wifi', 'kitchen', 'laundry'],
    images: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
      'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800',
    ],
    verified: true,
    featured: false,
    available: true,
    ownerId: 'owner-015',
  },
  {
    id: 'prop-016',
    title: 'غرفة خاصة مفروشة',
    description: 'غرفة خاصة مفروشة قرب جامعة قنا. المكان هادئ ومناسب للمذاكرة.',
    price: 700,
    priceType: 'per_room',
    location: 'قنا، حي الشرق، عمارة 7',
    city: 'قنا',
    coordinates: { lat: 26.1601, lng: 32.721 },
    nearTo: ['جامعة قنا'],
    distanceTo: { university: 'جامعة قنا', distance: 1.5 },
    type: 'private_room',
    rooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ['wifi', 'ac', 'kitchen', 'security'],
    images: [
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800',
      'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800',
    ],
    verified: true,
    featured: false,
    available: true,
    ownerId: 'owner-016',
  },

  // سوهاج
  {
    id: 'prop-017',
    title: 'سرير أرخص سعر في سوهاج',
    description: 'سرير في سكن طلابي بأرخص سعر في سوهاج. مناسب جداً للطلاب المقيدين.',
    price: 350,
    priceType: 'per_bed',
    location: 'سوهاج، شارع الجامعة، عمارة 2',
    city: 'سوهاج',
    coordinates: { lat: 26.5569, lng: 31.6948 },
    nearTo: ['جامعة سوهاج'],
    distanceTo: { university: 'جامعة سوهاج', distance: 1.0 },
    type: 'shared_bed',
    rooms: 3,
    beds: 6,
    bathrooms: 2,
    amenities: ['wifi', 'kitchen'],
    images: [
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800',
      'https://images.unsplash.com/photo-1522771753035-a0a1f66cd459?w=800',
    ],
    verified: true,
    featured: false,
    available: true,
    ownerId: 'owner-017',
  },
  {
    id: 'prop-018',
    title: 'غرفة خاصة بسعر معقول',
    description: 'غرفة خاصة بسعر معقول في سوهاج. قريبة من الجامعة والخدمات.',
    price: 650,
    priceType: 'per_room',
    location: 'سوهاج، حي الكوثر، عمارة 10',
    city: 'سوهاج',
    coordinates: { lat: 26.5619, lng: 31.6998 },
    nearTo: ['جامعة سوهاج'],
    distanceTo: { university: 'جامعة سوهاج', distance: 1.8 },
    type: 'private_room',
    rooms: 1,
    beds: 1,
    bathrooms: 1,
    amenities: ['wifi', 'ac', 'kitchen', 'security'],
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    verified: true,
    featured: false,
    available: true,
    ownerId: 'owner-018',
  },

  // الزقازيق
  {
    id: 'prop-019',
    title: 'سرير في سكن منظم',
    description: 'سرير في سكن طلابي منظم قرب جامعة الزقازيق.',
    price: 500,
    priceType: 'per_bed',
    location: 'الزقازيق، شارع الجامعة، عمارة 15',
    city: 'الزقازيق',
    coordinates: { lat: 30.5765, lng: 31.5041 },
    nearTo: ['جامعة الزقازيق'],
    distanceTo: { university: 'جامعة الزقازيق', distance: 1.2 },
    type: 'shared_bed',
    rooms: 2,
    beds: 4,
    bathrooms: 1,
    amenities: ['wifi', 'ac', 'kitchen', 'laundry'],
    images: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
      'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800',
    ],
    verified: true,
    featured: false,
    available: true,
    ownerId: 'owner-019',
  },
  {
    id: 'prop-020',
    title: 'شقة صغيرة للإيجار',
    description: 'شقة صغيرة مفروشة للإيجار قرب جامعة الزقازيق.',
    price: 1800,
    priceType: 'per_apartment',
    location: 'الزقازيق، حي أول، عمارة 8',
    city: 'الزقازيق',
    coordinates: { lat: 30.5815, lng: 31.5091 },
    nearTo: ['جامعة الزقازيق'],
    distanceTo: { university: 'جامعة الزقازيق', distance: 2.0 },
    type: 'full_apartment',
    rooms: 1,
    beds: 2,
    bathrooms: 1,
    amenities: ['wifi', 'ac', 'kitchen', 'security'],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    verified: true,
    featured: false,
    available: true,
    ownerId: 'owner-020',
  },
];

// بيانات الملاك
export const seedOwners = [
  { id: 'owner-001', name: 'أحمد محمد', email: 'ahmed.m@example.com', phone: '01001234567', role: 'OWNER' },
  { id: 'owner-002', name: 'محمد علي', email: 'mohamed.a@example.com', phone: '01011234567', role: 'OWNER' },
  { id: 'owner-003', name: 'خالد حسن', email: 'khaled.h@example.com', phone: '01021234567', role: 'OWNER' },
  { id: 'owner-004', name: 'سامي عبدالله', email: 'sami.a@example.com', phone: '01031234567', role: 'OWNER' },
  { id: 'owner-005', name: 'طارق إبراهيم', email: 'tarek.i@example.com', phone: '01041234567', role: 'OWNER' },
  { id: 'owner-006', name: 'يوسف محمود', email: 'youssef.m@example.com', phone: '01051234567', role: 'OWNER' },
  { id: 'owner-007', name: 'عمر سعيد', email: 'omar.s@example.com', phone: '01061234567', role: 'OWNER' },
  { id: 'owner-008', name: 'كريم فؤاد', email: 'karim.f@example.com', phone: '01071234567', role: 'OWNER' },
  { id: 'owner-009', name: 'إبراهيم ناصر', email: 'ibrahim.n@example.com', phone: '01081234567', role: 'OWNER' },
  { id: 'owner-010', name: 'حسن علي', email: 'hassan.a@example.com', phone: '01091234567', role: 'OWNER' },
  { id: 'owner-011', name: 'مصطفى كمال', email: 'mostafa.k@example.com', phone: '01101234567', role: 'OWNER' },
  { id: 'owner-012', name: 'عبدالرحمن صالح', email: 'abdelrahman.s@example.com', phone: '01111234567', role: 'OWNER' },
  { id: 'owner-013', name: 'محمود رمزي', email: 'mahmoud.r@example.com', phone: '01121234567', role: 'OWNER' },
  { id: 'owner-014', name: 'أشرف حمدي', email: 'ashraf.h@example.com', phone: '01131234567', role: 'OWNER' },
  { id: 'owner-015', name: 'رأفت عباس', email: 'raafat.a@example.com', phone: '01141234567', role: 'OWNER' },
  { id: 'owner-016', name: 'نبيل فؤاد', email: 'nabil.f@example.com', phone: '01151234567', role: 'OWNER' },
  { id: 'owner-017', name: 'جلال الدين', email: 'galal.e@example.com', phone: '01161234567', role: 'OWNER' },
  { id: 'owner-018', name: 'حاتم مراد', email: 'hatem.m@example.com', phone: '01171234567', role: 'OWNER' },
  { id: 'owner-019', name: 'وليد سعد', email: 'walid.s@example.com', phone: '01181234567', role: 'OWNER' },
  { id: 'owner-020', name: 'فؤاد حلمي', email: 'fouad.h@example.com', phone: '01191234567', role: 'OWNER' },
];

// بيانات المغتربين
export const seedExpats = [
  { id: 'expat-001', name: 'أحمد السوداني', email: 'ahmed.sudan@example.com', phone: '01201234567', role: 'EXPAT', preferences: { university: 'cairo', budget: 1000, type: 'shared_bed', priorities: ['near_university', 'cheap_price'] } },
  { id: 'expat-002', name: 'سارة الأردنية', email: 'sarah.jordan@example.com', phone: '01211234567', role: 'EXPAT', preferences: { university: 'auc', budget: 2500, type: 'private_room', priorities: ['safety', 'strong_wifi'] } },
  { id: 'expat-003', name: 'يوسف اليمني', email: 'youssef.yemen@example.com', phone: '01221234567', role: 'EXPAT', preferences: { university: 'alexandria', budget: 800, type: 'shared_bed', priorities: ['cheap_price', 'quiet'] } },
  { id: 'expat-004', name: 'فاطمة المغربية', email: 'fatima.morocco@example.com', phone: '01231234567', role: 'EXPAT', preferences: { university: 'mansoura', budget: 1200, type: 'private_room', priorities: ['near_university', 'safety'] } },
];

// المحادثات الواقعية
export const seedMessages = [
  {
    id: 'msg-001',
    content: 'السلام عليكم، عايز أعرف السكن ده متاح لسه؟ أنا طالب جديد في كلية الطب',
    senderId: 'expat-001',
    receiverId: 'owner-001',
    propertyId: 'prop-001',
    createdAt: new Date('2025-02-20T10:00:00'),
    read: true,
  },
  {
    id: 'msg-002',
    content: 'وعليكم السلام، أهلاً بيك! آه متاح. إنت في السنة الأولى؟',
    senderId: 'owner-001',
    receiverId: 'expat-001',
    propertyId: 'prop-001',
    createdAt: new Date('2025-02-20T10:05:00'),
    read: true,
  },
  {
    id: 'msg-003',
    content: 'أيوة، لسه واصل القاهرة من اسبوع. السكن قريب من الجامعة قد إيه بالظبط؟',
    senderId: 'expat-001',
    receiverId: 'owner-001',
    propertyId: 'prop-001',
    createdAt: new Date('2025-02-20T10:10:00'),
    read: true,
  },
  {
    id: 'msg-004',
    content: 'مشي 12 دقيقة، أو 5 دقايق توك توك. فيه مترو محرم بيك كمان قريب',
    senderId: 'owner-001',
    receiverId: 'expat-001',
    propertyId: 'prop-001',
    createdAt: new Date('2025-02-20T10:15:00'),
    read: true,
  },
  {
    id: 'msg-005',
    content: 'ممتاز. ممكن أجي أشوفه السبت الجاي؟',
    senderId: 'expat-001',
    receiverId: 'owner-001',
    propertyId: 'prop-001',
    createdAt: new Date('2025-02-20T10:20:00'),
    read: true,
  },
  {
    id: 'msg-006',
    content: 'تمام، الساعة كام؟',
    senderId: 'owner-001',
    receiverId: 'expat-001',
    propertyId: 'prop-001',
    createdAt: new Date('2025-02-20T10:25:00'),
    read: true,
  },
  {
    id: 'msg-007',
    content: 'العاشرة صباحاً مناسب؟',
    senderId: 'expat-001',
    receiverId: 'owner-001',
    propertyId: 'prop-001',
    createdAt: new Date('2025-02-20T10:30:00'),
    read: true,
  },
  {
    id: 'msg-008',
    content: 'ماشي، ابعتلي رقمك وأسيب لك العنوان التفصيلي',
    senderId: 'owner-001',
    receiverId: 'expat-001',
    propertyId: 'prop-001',
    createdAt: new Date('2025-02-20T10:35:00'),
    read: false,
  },
  {
    id: 'msg-009',
    content: 'مساء الخير، السكن ده فيه AC؟ والإنترنت قوي؟',
    senderId: 'expat-002',
    receiverId: 'owner-004',
    propertyId: 'prop-004',
    createdAt: new Date('2025-02-21T18:00:00'),
    read: true,
  },
  {
    id: 'msg-010',
    content: 'مساء النور، آه فيه AC سبلت في الأوضة. الإنترنت fiber 100 ميجا',
    senderId: 'owner-004',
    receiverId: 'expat-002',
    propertyId: 'prop-004',
    createdAt: new Date('2025-02-21T18:10:00'),
    read: true,
  },
  {
    id: 'msg-011',
    content: 'كويس. أنا دكتور في التكليف في القصر العيني، الشفتات بتاعتي بتكون بالليل. السكن هادي؟',
    senderId: 'expat-002',
    receiverId: 'owner-004',
    propertyId: 'prop-004',
    createdAt: new Date('2025-02-21T18:15:00'),
    read: true,
  },
  {
    id: 'msg-012',
    content: 'آه هادي جداً، في الدور الأخير ومفيش جيران أطفال. معظم السكان طلاب',
    senderId: 'owner-004',
    receiverId: 'expat-002',
    propertyId: 'prop-004',
    createdAt: new Date('2025-02-21T18:20:00'),
    read: true,
  },
  {
    id: 'msg-013',
    content: 'تمام، ممكن نعمل عقد؟',
    senderId: 'expat-002',
    receiverId: 'owner-004',
    propertyId: 'prop-004',
    createdAt: new Date('2025-02-21T18:25:00'),
    read: false,
  },
  {
    id: 'msg-014',
    content: 'مرحباً، أنا طالبة من المغرب، عندي سؤال: السكن security كويس؟',
    senderId: 'expat-004',
    receiverId: 'owner-010',
    propertyId: 'prop-010',
    createdAt: new Date('2025-02-22T14:00:00'),
    read: true,
  },
  {
    id: 'msg-015',
    content: 'أهلاً وسهلاً! آه فيه Porter على البوابة 24 ساعة، وكاميرات في العمارة',
    senderId: 'owner-010',
    receiverId: 'expat-004',
    propertyId: 'prop-010',
    createdAt: new Date('2025-02-22T14:05:00'),
    read: true,
  },
  {
    id: 'msg-016',
    content: 'ممتاز. فيه مطبخ مجهز؟ بحب أطبخ',
    senderId: 'expat-004',
    receiverId: 'owner-010',
    propertyId: 'prop-010',
    createdAt: new Date('2025-02-22T14:10:00'),
    read: true,
  },
  {
    id: 'msg-017',
    content: 'آه مطبخ كامل بكل الأجهزة، والمغتربين اللي معاكي بيحبوا يطبخوا برضه',
    senderId: 'owner-010',
    receiverId: 'expat-004',
    propertyId: 'prop-010',
    createdAt: new Date('2025-02-22T14:15:00'),
    read: true,
  },
  {
    id: 'msg-018',
    content: 'حلو أوي! ممكن أحجز بكرة؟',
    senderId: 'expat-004',
    receiverId: 'owner-010',
    propertyId: 'prop-010',
    createdAt: new Date('2025-02-22T14:20:00'),
    read: false,
  },
];

// التقييمات الواقعية
export const seedReviews: Review[] = [
  {
    id: 'review-001',
    bookingId: 'book-001',
    propertyId: 'prop-001',
    reviewerId: 'expat-001',
    ownerId: 'owner-001',
    photosAccuracy: 5,
    descriptionAccuracy: 5,
    amenitiesMatch: 4,
    safetyAccuracy: 5,
    overallRating: 5,
    wouldRecommend: true,
    comment: 'الصور كانت بالظبط زي الواقع، المالك محترم جداً والسكن نظيف. أنصح بيه بشدة!',
    trustScore: 95,
    visitPhotos: [],
    visitDate: new Date('2025-02-15'),
    createdAt: new Date('2025-02-15'),
  },
  {
    id: 'review-002',
    bookingId: 'book-002',
    propertyId: 'prop-004',
    reviewerId: 'expat-002',
    ownerId: 'owner-004',
    photosAccuracy: 4,
    descriptionAccuracy: 5,
    amenitiesMatch: 5,
    safetyAccuracy: 5,
    overallRating: 5,
    wouldRecommend: true,
    comment: 'AC شغال كويس، بس الإنترنت أحياناً بيبطأ شوية. بشكل عام تجربة ممتازة.',
    trustScore: 92,
    visitPhotos: [],
    visitDate: new Date('2025-02-18'),
    createdAt: new Date('2025-02-18'),
  },
  {
    id: 'review-003',
    bookingId: 'book-003',
    propertyId: 'prop-010',
    reviewerId: 'expat-004',
    ownerId: 'owner-010',
    photosAccuracy: 5,
    descriptionAccuracy: 4,
    amenitiesMatch: 5,
    safetyAccuracy: 5,
    overallRating: 5,
    wouldRecommend: true,
    comment: 'الأمان ممتاز والمطبخ مجهز بكل حاجة. المالك متعاون جداً.',
    trustScore: 93,
    visitPhotos: [],
    visitDate: new Date('2025-02-20'),
    createdAt: new Date('2025-02-20'),
  },
  {
    id: 'review-004',
    bookingId: 'book-004',
    propertyId: 'prop-002',
    reviewerId: 'expat-003',
    ownerId: 'owner-002',
    photosAccuracy: 5,
    descriptionAccuracy: 5,
    amenitiesMatch: 5,
    safetyAccuracy: 5,
    overallRating: 5,
    wouldRecommend: true,
    comment: 'سكن ممتاز وقريب جداً من المترو. الغرفة واسعة والتهوية كويسة.',
    trustScore: 100,
    visitPhotos: [],
    visitDate: new Date('2025-02-10'),
    createdAt: new Date('2025-02-10'),
  },
  {
    id: 'review-005',
    bookingId: 'book-005',
    propertyId: 'prop-006',
    reviewerId: 'expat-001',
    ownerId: 'owner-006',
    photosAccuracy: 4,
    descriptionAccuracy: 4,
    amenitiesMatch: 3,
    safetyAccuracy: 5,
    overallRating: 4,
    wouldRecommend: true,
    comment: 'المنظر على البحر يجنن! بس الإنترنت كان فيه مشكلة شوية أول يومين.',
    trustScore: 85,
    visitPhotos: [],
    visitDate: new Date('2025-02-12'),
    createdAt: new Date('2025-02-12'),
  },
  {
    id: 'review-006',
    bookingId: 'book-006',
    propertyId: 'prop-013',
    reviewerId: 'expat-003',
    ownerId: 'owner-013',
    photosAccuracy: 3,
    descriptionAccuracy: 4,
    amenitiesMatch: 4,
    safetyAccuracy: 4,
    overallRating: 3,
    wouldRecommend: false,
    comment: 'السكن قديم شوية والصور كانت متجملة بزيادة. بس السعر مناسب للميزانية الضعيفة.',
    trustScore: 70,
    visitPhotos: [],
    visitDate: new Date('2025-02-05'),
    createdAt: new Date('2025-02-05'),
  },
];

// الحجوزات الواقعية
export const seedBookings: Booking[] = [
  {
    id: 'book-010',
    propertyId: 'prop-001',
    expatId: 'expat-001',
    status: 'pending',
    visitDate: new Date('2025-03-01T10:00:00'),
    notes: 'عايز أشوف الحمام والمطبخ كويس',
    createdAt: new Date('2025-02-24'),
  },
  {
    id: 'book-011',
    propertyId: 'prop-010',
    expatId: 'expat-004',
    status: 'confirmed',
    visitDate: new Date('2025-02-28T14:00:00'),
    createdAt: new Date('2025-02-23'),
  },
  {
    id: 'book-012',
    propertyId: 'prop-004',
    expatId: 'expat-002',
    status: 'confirmed',
    visitDate: new Date('2025-02-27T18:00:00'),
    createdAt: new Date('2025-02-22'),
  },
];

// إحصائيات الملاك
export const seedOwnerStats: OwnerStats[] = [
  {
    id: 'stats-001',
    ownerId: 'owner-001',
    totalReviews: 5,
    averageTrustScore: 95,
    photosAccuracy: 98,
    descriptionAccuracy: 95,
    amenitiesMatch: 92,
    safetyAccuracy: 95,
    overallRating: 4.8,
    badge: 'trusted'
  },
  {
    id: 'stats-004',
    ownerId: 'owner-004',
    totalReviews: 3,
    averageTrustScore: 92,
    photosAccuracy: 90,
    descriptionAccuracy: 95,
    amenitiesMatch: 95,
    safetyAccuracy: 90,
    overallRating: 4.5,
    badge: 'verified'
  },
  {
    id: 'stats-010',
    ownerId: 'owner-010',
    totalReviews: 4,
    averageTrustScore: 93,
    photosAccuracy: 95,
    descriptionAccuracy: 90,
    amenitiesMatch: 95,
    safetyAccuracy: 92,
    overallRating: 4.6,
    badge: 'verified'
  },
  {
    id: 'stats-013',
    ownerId: 'owner-013',
    totalReviews: 2,
    averageTrustScore: 70,
    photosAccuracy: 65,
    descriptionAccuracy: 75,
    amenitiesMatch: 70,
    safetyAccuracy: 70,
    overallRating: 3.2,
    badge: 'flagged'
  },
];
